# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
homebrew_installed_packages:
  - tmux
  - git
  - gpg
  - pinentry-mac
  - node
  - curl
  - act
  - asciiquarium
  - bat
  - openjdk
  - pygments
  - neofetch
  - pre-commit
  - rsync
  - tldr
  - fzf
  - tmux

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_apps:
  - dash
  - homebrew/cask-versions/iterm2-beta  # todo change to iterm2 as soon as v3.5 releases
  - linearmouse
  - hiddenbar
  # - mambaforge  # takes long...
  - micromamba
  - raycast
  - insomnia
  - discord
  - docker
  - mactex-no-gui
  - vlc

homebrew_cask_uninstalled_apps:
  # The Bitwarden app needs to be installed from the App Store in order for the Safari Extension to work.
  - bitwarden

config_folder:
  - git
  - iterm2
  - linearmouse
  - tmux
