---
- hosts: all
  name: Dotfiles provision

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config-files/*.config.yml"
      tags: ['always']

  tasks:
    - name: Ensure OSX command line tools are installed.
      ansible.builtin.import_role:
        name: elliotweiser.osx-command-line-tools
    - name: Ensure Homebrew is installed and configured.
      ansible.builtin.import_role:
        name: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - name: Ensure Oh My Zsh is installed and configured.
      ansible.builtin.import_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ ansible_user }}"
      tags: ['oh-my-zsh']
    - name: Perform oh-my-zsh tasks.
      ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      tags: ['oh-my-zsh']
    - name: Perform configuration tasks.
      ansible.builtin.import_tasks: tasks/configure.yml
      tags: ['configure']
    - name: Ensure Dock is configured.
      tags: ['dock', 'configure']
      ansible.builtin.import_role:
        name: geerlingguy.mac.dock
    # - import_tasks: tasks/install.yml
    #   tags: ['programs', 'build']


# todos:
# todo install conda correctly
# install saucecodepro, mesolgs nf font
# dotfile integration
# iterm shell integration
# maybe JDownloader2?
# maybe Negative (PDF Viewer)?
# maybe OneDrive?
# adobe products
# maybe ausweisapp2?
# Parallels Desktop
# Refined GitHub
# obs
# HandBrake configuration


# from App Store:
# Accelerate
# Banking4
# Bitwarden
# GARDENA
# GoodNotes
# Grammarly
# Navigator
# TV Time
# Prologue
# Xcode
# Class Timetable
