---
- hosts: all
  name: Dotfiles provision

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/*.config.yml"
      tags: ['always']

  tasks:
    - name: Ensure OSX command line tools are installed.
      ansible.builtin.import_role:
        name: elliotweiser.osx-command-line-tools
    - name: Ensure Homebrew is installed and configured.
      ansible.builtin.import_role:
        name: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - name: Ensure Oh My Zsh is installed and configured.
      ansible.builtin.import_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ ansible_user }}"
      tags: ['oh-my-zsh']
    - ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      tags: ['oh-my-zsh']
    - ansible.builtin.import_tasks: tasks/configure.yml
      tags: ['configure']
    # - ansible.builtin.import_role:
    #     name: geerlingguy.mac.dock
    #   tags: ['dock']
    # - import_tasks: tasks/install.yml
    #   tags: ['programs', 'build']


# todos:
# install latex(?)
# after micromamba brew cask installation, initialize
# fix micromamba and conda shell hooks (some files need to be there first)
# install saucecodepro, mesolgs nf font
# dotfile integration
# iterm shell integration
