- name: Ensure iTerm2 is configured to load preferences from custom location.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    value: true
    type: boolean
    state: present
- name: Ensure iTerm2 custom preferences location is set.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    value: "{{ config_home }}/iterm2"
    type: string
    state: present
- name: Ensure .config dotfiles are set.
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ config_home }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0744
  loop: "{{ config_folder }}"
- name: Ensure .gnupg dotfiles are set.
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/gnupg/"
    dest: "{{ ansible_user_dir }}/.gnupg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensure .condarc is set.
  ansible.builtin.template:
    src: "{{ dotfiles_dir }}/conda/condarc.j2"
    dest: "{{ ansible_user_dir }}/.condarc"
    # todo move to $XDG_CONFIG_HOME/conda/condarc as soon as https://github.com/mamba-org/mamba/issues/1916 is done
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensures .mamba/auth dir exists.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.mamba/auth"
    state: directory
    recurse: true
- name: Ensure mamba authentication.json is set.
  ansible.builtin.template:
    src: "{{ dotfiles_dir }}/conda/authentication.json.j2"
    dest: "{{ ansible_user_dir }}/.mamba/auth/authentication.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensure .pypirc is set.
  ansible.builtin.template:
    src: "{{ dotfiles_dir }}/pypi/pypirc.j2"
    dest: "{{ ansible_user_dir }}/.pypirc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensure .ghc dir exists.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ghc"
    state: directory
    recurse: true
- name: Ensure ghci.conf is set.
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/ghc/ghci.conf"
    # the current brew version of ghc does not support $XDG_CONFIG_HOME
    # but since ghc 9.4.1 it is supported (https://downloads.haskell.org/~ghc/9.4.1/docs/users_guide/9.4.1-notes.html?highlight=xdg)
    # https://gitlab.haskell.org/ghc/ghc/-/commit/763d28551de32377a1dca8bdde02979e3686f400
    # https://downloads.haskell.org/ghc/latest/docs/users_guide/ghci.html#the-ghci-files
    # -> wait for ghc >= 9.4.1 to be available via brew
    # see https://github.com/Homebrew/homebrew-core/pull/110865
    # dest: "{{ config_home }}/.ghci"
    dest: "{{ ansible_user_dir }}/.ghc/ghci.conf"
    mode: 0644
- name: Ensure US with German umlauts keyboard layout is present.
  become: true
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/keyboard-layouts/us-with-german-umlauts/US-with-German-Umlauts.bundle"
    dest: "/Library/Keyboard Layouts/"
    owner: root
    group: wheel
    mode: 0755
  # you still need to activate this keyboard under System Preferences
  # -> Keyboard -> Input Sources in the English category
