- name: Ensure iTerm2 is configured to load preferences from custom location.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    value: true
    type: boolean
    state: present
- name: Ensure iTerm2 custom preferences location is set.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    value: "{{ config_home }}/iterm2"
    type: string
    state: present
- name: Ensure .config dotfiles are set.
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/{{ item }}"
    dest: "{{ config_home }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0744
  loop: "{{ config_folder }}"
- name: Ensure .gnupg dotfiles are set.
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/gnupg/"
    dest: "{{ ansible_user_dir }}/.gnupg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensure .condarc is set.
  ansible.builtin.template:
    src: "{{ playbook_dir }}/dotfiles/conda/condarc.j2"
    dest: "{{ ansible_user_dir }}/.condarc"
    # todo move to $XDG_CONFIG_HOME/conda/condarc as soon as https://github.com/mamba-org/mamba/issues/1916 is done
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
- name: Ensures .mamba/auth dir exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.mamba/auth"
    state: directory
    recurse: true
- name: Ensure mamba authentication.json is set.
  ansible.builtin.template:
    src: "{{ playbook_dir }}/dotfiles/conda/authentication.json.j2"
    dest: "{{ ansible_user_dir }}/.mamba/auth/authentication.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: 0600
