- name: Ensure Powerlevel10k theme is available.
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
- name: Ensure oh-my-zsh plugins are available.
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  with_items:
    - { name: fzf-zsh-plugin, repo: https://github.com/unixorn/fzf-zsh-plugin.git }
    - { name: zsh-syntax-highlighting, repo: https://github.com/zsh-users/zsh-syntax-highlighting.git }
    - { name: zsh-autosuggestions, repo: https://github.com/zsh-users/zsh-autosuggestions.git }
- name: Ensure custom zsh files are available.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom"
    mode: 0744
  with_fileglob:
    - "{{ playbook_dir }}/dotfiles/oh-my-zsh/custom/*.zsh"
