- name: Get commit SHA of the local repo.
  local_action:
    module: git
    repo: "{{ item.repo }}"
    dest: "{{ playbook_dir }}/dotfiles/oh-my-zsh/custom/{{ item.path }}"
    clone: no
    update: no
  register: gitresult
  with_items:
    - { repo: https://github.com/romkatv/powerlevel10k.git, path: themes/powerlevel10k }
    - { repo: https://github.com/zsh-users/zsh-autosuggestions.git, path: plugins/zsh-autosuggestions }
    - { repo: https://github.com/unixorn/fzf-zsh-plugin.git, path: plugins/fzf-zsh-plugin }
    - { repo: https://github.com/zsh-users/zsh-syntax-highlighting.git, path: plugins/zsh-syntax-highlighting }
- name: Ensure themes and plugins are available.
  # This is a shallow git clone with a specific SHA checked out, cf https://stackoverflow.com/a/43136160/18839600
  ansible.builtin.shell:
    cmd: |
      mkdir -p "{{ item.path }}"
      cd "{{ item.path }}"
      git init
      git remote add origin "{{ item.repo }}"
      git fetch --depth 1 origin {{ item.sha }}
      git checkout FETCH_HEAD
    creates: "{{ item.path }}"
    chdir: "{{ ansible_user_dir }}/.oh-my-zsh/custom"
  with_items: "{{ gitresult.results | mapattributes(['item.repo', 'item.path', 'after'], ['repo', 'path', 'sha']) }}"
- name: Ensure custom zsh files are available.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom"
    mode: 0744
  with_fileglob:
    - "{{ playbook_dir }}/dotfiles/oh-my-zsh/custom/*.zsh"
