# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
homebrew_installed_packages:
  - act
  - ansible
  - ansible-lint
  - asciiquarium
  - bat
  - curl
  - exa
  - fzf
  - git
  - gpg
  - htop
  - neofetch
  - node
  - openjdk
  - pinentry-mac
  - pre-commit
  - pygments
  - rsync
  - tldr
  - tmux
  - yt-dlp

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_apps:
  - anki
  - homebrew/homebrew-cask-drivers/canon-eos-webcam-utility
  - dash
  - devtoys
  - discord
  - docker
  - element
  - google-chrome
  - homebrew/cask-fonts/font-meslo-lg-nerd-font
  - handbrake
  - hiddenbar
  - insomnia
  - homebrew/cask-versions/iterm2-beta  # todo change to iterm2 as soon as v3.5 releases
  - linearmouse
  # - homebrew/homebrew-cask-drivers/logi-options-plus # you need to execute the installer manually...
  - mactex-no-gui
  # - mambaforge
  - micromamba
  # - microsoft-office
  - nextcloud
  # - nordvpn
  - homebrew/cask-versions/parallels17
  - plex
  - portfolioperformance
  - raycast
  - rectangle
  - shottr
  - slack
  - slidepilot
  - spotify
  - steam
  - telegram
  - threema
  - visual-studio-code
  - vlc
  - whatsapp
  - zoom
  # JetBrains Products
  - jetbrains-toolbox
  # - pycharm
  # - clion
  # - intellij-idea

homebrew_cask_uninstalled_apps:
  # The Bitwarden app needs to be installed from the App Store in order for the Safari Extension to work.
  - bitwarden
  - microsoft-office
  - nordvpn
